default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: "db/test.sqlite3"

production:
  <<: *default
  Database: d6m36ent66rd1i
  Username: fvbrpuokdiqedt
  Host: ec2-44-209-158-64.compute-1.amazonaws.com
  Password: 8b034761024c13c5435568d609a9a95835e2bc3bd455b3f808c0d27771baccf4