default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  Host: ec2-44-209-158-64.compute-1.amazonaws.com
  Database: d57sdhkj8ao4di  
  User: tpiaagduwhkhjq
  Password: 90dc2a016d1c4c31a4bd25952c592e8ddc4870fb1da86f705f664622a34969ee

